language: node_js 
env:
    global:
        secure: "VskenIWvoOYYblzJzpVpTzgx/DluxocGFjHDFI+RsP1U1IaS5yLlo0Uza6Yh7+g7mDixvL8z9joOyX7oQ4PrnoNjE0h3oGyYrQ4fEiOvzZHDsHTwXYPysySs3wiTBD6rjfgtXHM7ylgPtFBR7MJdttnrKCgeQd+rNl+tZe4pSqY="
        
cache: 
  - apt
  - npm
    
matrix:
  fast_finish: true
  
# whitelist
branches:
  only:
    - master
    
before_install:
  - chmod u+x ./travis.sh

install:
  - echo let us start

script:
  - bash -x ./travis.sh
  
#after_success:
#  -  bash -e ./BANK/travis_and_github/update-gh-pages.sh

